### ISSUE TITLE
Login TODO

### ISSUE THREAD

**Issue by thelight0804** [thelight0804/massi_dot_com#17]
- [x] Redux 설정
- [x] 자동 로그인
- [x] 로그인 규칙에 따라 네비게이션 바 변경
- [x] 로그아웃 구현
- [x] 식당 추가 할 때 UID 추가
- [x] 메뉴 등록 접근 시 로그인 중인지 확인
